version: '3.8'

services:
  db:
    container_name: db
    restart: always
    image: postgres:10.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    # volumes:
    #   - db:/var/lib/postgresql/data
  back:
    container_name: back
    restart: always
    build: back/
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    volumes:
      - ./back:/app
      - ./back/node_modules:/app/node_modules
    depends_on:
      - db
  front:
    container_name: front
    restart: always
    build: front/
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    volumes:
      - ./front:/app
      - ./front/node_modules:/app/node_modules
    depends_on:
      - back