version: '3.8'

services:
  db:
    container_name: db
    restart: always
    image: postgres:10.17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n8_fullstack_assessment
    # volumes:
    #   - db:/var/lib/postgresql/data

  back:
    container_name: back
    restart: always
    command: npm run start
    build: back/
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
  back-dev:
    container_name: back-dev
    restart: always
    command: npm run start:dev
    build: back/
    ports:
      - "3001:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: n8_fullstack_assessment
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev

  front:
    container_name: front
    restart: always
    build: front/
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - back