version: '3.8'

services:
  db:
    container_name: db
    restart: always
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n8_fullstack_assessment
    volumes:
      - pg-data:/var/lib/postgresql/data

  back:
    container_name: back
    restart: always
    build: back/
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      PORT: 3000
      CORS_ORIGIN: http://localhost:8080
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: n8_fullstack_assessment
    depends_on:
      - db

  front:
    container_name: front
    restart: always
    build: front/
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
    depends_on:
      - back

volumes:
  pg-data: